h5py:
  - 2.9.0
hdf5:
  - 1.10.4
networkx:
  - 2.3*
numpy:
  - 1.14
pandas:
  - 0.24
python:
  - 3.7
pyqt:
  - 5.6
qt:
  - 5.6
sklearn:
  - 0.20
tifffile:
  - 0.4.post2
vigra:
  - 1.11
pytest:
  - 3.10
# fix macOS build, broken jpeg=9b
pillow:
  - 5.3.0

pin_run_as_build:
  h5py: x.x
  hdf5: x.x.x
  networkx: x.x
  numpy: x.x
  pandas: x.x
  python: x.x
  pyqt: x.x
  qt: x.x
  tifffile: x.x.x
  vigra: x.x
  pytest: x.x
  pillow: x.x
